// Generated by tools/generate.py — do not edit.

function freeze(o) {
    if (o && typeof o === 'object')
        Object.values(o).forEach(freeze);
    return Object.freeze(o);
}

export const SPRINGS = freeze({
  "ComposeSpringDefault": {
    "damping": 1.0,
    "stiffness": 1500.0
  },
  "DefaultEffects": {
    "damping": 1.0,
    "stiffness": 1600.0
  },
  "DefaultSpatial": {
    "damping": 0.8,
    "stiffness": 380.0
  },
  "DialogCollapseScale": {
    "damping": 0.9,
    "stiffness": 380.0
  },
  "DialogCollapseX": {
    "damping": 0.9,
    "stiffness": 380.0
  },
  "DialogCollapseY": {
    "damping": 0.87,
    "stiffness": 380.0
  },
  "DialogLaunchPosition": {
    "damping": 1.1,
    "stiffness": 700.0
  },
  "DialogLaunchScale": {
    "damping": 1.3,
    "stiffness": 700.0
  },
  "FastEffects": {
    "damping": 1.0,
    "stiffness": 3800.0
  },
  "FastSpatial": {
    "damping": 0.6,
    "stiffness": 800.0
  },
  "GestureHomeScale": {
    "damping": 0.99,
    "stiffness": 500.0
  },
  "GestureHomeX": {
    "damping": 0.965,
    "stiffness": 450.0
  },
  "GestureHomeY": {
    "damping": 0.95,
    "stiffness": 400.0
  },
  "NotificationSnapBack": {
    "damping": 0.52,
    "stiffness": 550.0
  },
  "NotificationTranslation": {
    "damping": 0.68,
    "stiffness": 380.0
  },
  "ShadeExpansionMeasured": {
    "damping": 0.925,
    "stiffness": 197.0
  },
  "SlowEffects": {
    "damping": 1.0,
    "stiffness": 800.0
  },
  "SlowSpatial": {
    "damping": 0.8,
    "stiffness": 200.0
  },
  "VolumeDialog": {
    "damping": 0.9,
    "stiffness": 700.0
  }
});

export const THRESHOLDS = freeze({
  "degree": 0.1,
  "px": 0.5,
  "unit": 0.01
});

export const PATTERNS = freeze({
  "containerTransform": {
    "fadeIn": {
      "end": 0.25,
      "start": 0.0
    },
    "fadeReturn": {
      "end": 0.9,
      "start": 0.6
    },
    "fit": "AUTO",
    "mode": "IN",
    "scaleMask": {
      "end": 1.0,
      "start": 0.0
    },
    "scaleMaskReturn": {
      "end": 0.9,
      "start": 0.0
    },
    "shapeMask": {
      "end": 0.75,
      "start": 0.0
    },
    "shapeMaskReturn": {
      "end": 0.9,
      "start": 0.3
    },
    "springEffects": "DefaultEffects",
    "springSpatial": "DefaultSpatial"
  },
  "fade": {
    "exitWithoutScale": true,
    "fadeInEnd": 0.3,
    "incomingScale": 0.8,
    "springEnter": "DefaultSpatial",
    "springEnterEffects": "DefaultEffects",
    "springExit": "FastEffects"
  },
  "fadeThrough": {
    "incomingScale": 0.92,
    "outgoingShare": 0.35,
    "springEffects": "FastEffects",
    "springSpatial": "DefaultSpatial"
  },
  "morphCorners": {
    "spring": "FastSpatial",
    "springEffects": "FastEffects"
  },
  "sharedAxis": {
    "fadeIn": {
      "end": 1.0,
      "start": 0.35
    },
    "fadeOut": {
      "end": 0.35,
      "start": 0.0
    },
    "scaleZ": {
      "incomingStart": 0.8,
      "outgoingEnd": 1.1
    },
    "slidePx": 30,
    "springEffects": "DefaultEffects",
    "springSpatial": "DefaultSpatial"
  }
});

// Android 17 (android-source.json): fixed-duration curves (curve.js) and motion parameters.
export const CURVES = freeze({
  "AccelerateDecelerate": {
    "segments": [
      [
        0,
        0,
        0.3628,
        -0.0016,
        0.6372,
        1.0016,
        1,
        1
      ]
    ]
  },
  "Emphasized": {
    "segments": [
      [
        0,
        0,
        0.05,
        0,
        0.133333,
        0.06,
        0.166666,
        0.4
      ],
      [
        0.166666,
        0.4,
        0.208333,
        0.82,
        0.25,
        1,
        1,
        1
      ]
    ]
  },
  "FastOutSlowIn": {
    "segments": [
      [
        0,
        0,
        0.4,
        0,
        0.2,
        1,
        1,
        1
      ]
    ]
  },
  "FastOutSlowInReverse": {
    "segments": [
      [
        0,
        0,
        0.8,
        0,
        0.6,
        1,
        1,
        1
      ]
    ]
  },
  "Linear": {
    "segments": [
      [
        0,
        0,
        0.333333,
        0.333333,
        0.666667,
        0.666667,
        1,
        1
      ]
    ]
  },
  "Standard": {
    "segments": [
      [
        0,
        0,
        0.2,
        0,
        0,
        1,
        1,
        1
      ]
    ]
  }
});

export const ANDROID = freeze({
  "activityOpen": {
    "alphaDelayMs": 50,
    "alphaDurationMs": 83,
    "curve": "Emphasized",
    "durationMs": 450,
    "slideDp": 96
  },
  "banner": {
    "durationMs": 400,
    "enter": "FastOutSlowIn",
    "exit": "FastOutSlowInReverse"
  },
  "density": 0.7777777777777778,
  "dialog": {
    "closeScale": "DialogCollapseScale",
    "closeX": "DialogCollapseX",
    "closeY": "DialogCollapseY",
    "contentEnterEnd": 0.985,
    "contentEnterStart": 0.85,
    "contentExitEnd": 0.8,
    "contentExitStart": 0.0,
    "openPosition": "DialogLaunchPosition",
    "openScale": "DialogLaunchScale"
  },
  "launch": {
    "alphaDelayMs": 25,
    "alphaDurationMs": 50,
    "curve": "Emphasized",
    "durationMs": 500
  },
  "notifications": {
    "spring": "NotificationTranslation"
  },
  "osd": {
    "alphaAllOrNothing": true,
    "spring": "VolumeDialog"
  },
  "qsShade": {
    "closeDp": 177,
    "cutoffDp": 150,
    "openDp": 164,
    "spring": "ShadeExpansionMeasured"
  },
  "returnHome": {
    "scale": "GestureHomeScale",
    "x": "GestureHomeX",
    "y": "GestureHomeY"
  },
  "switch": {
    "iconDp": 16,
    "morphCurve": "Emphasized",
    "morphHeightDp": 22,
    "morphLongMs": 150,
    "morphShortMs": 100,
    "morphWidthDp": 32,
    "pressCurve": "Standard",
    "pressMs": 100,
    "slideCurve": "AccelerateDecelerate",
    "slideMs": 250,
    "thumbDp": 24,
    "thumbPressedDp": 28
  },
  "tile": {
    "bounceDp": 8,
    "bounceMaxWaitMs": 1000,
    "bounceMinRatio": 0.75,
    "bounceSpring": "ComposeSpringDefault",
    "spring": "ComposeSpringDefault"
  }
});
