#!/usr/bin/env python3
"""Reference Python port of the Compose springs (mass 1).

Upstream sources: androidx/androidx compose/animation/animation-core SpringSimulation.kt and
SpringEstimation.kt (Apache-2.0, see NOTICE.md), at the commit pinned in shared/data/PROVENANCE.md.
Kotlin Double arithmetic: division by zero, log(0) and overflowing exp give inf/nan instead of
raising, hence the small helpers _div, _ln, _exp.
"""
import argparse
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS_JSON = ROOT / "shared" / "data" / "m3e-tokens.json"
SPRING_NAMES = ["DefaultSpatial", "FastSpatial", "SlowSpatial", "DefaultEffects", "FastEffects", "SlowEffects"]

MAX_LONG = 2**63 - 1
MAX_LONG_MILLIS = MAX_LONG // 1_000_000  # SpringEstimation.kt:32


# --- Kotlin IEEE semantics ---------------------------------------------------
def _div(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        if a == 0 or a != a:
            return math.nan
        return math.copysign(math.inf, a) * (math.copysign(1.0, b))


def _ln(x):
    if x != x or x < 0:
        return math.nan
    if x == 0:
        return -math.inf
    return math.log(x)


def _exp(x):
    try:
        return math.exp(x)
    except OverflowError:
        return math.inf


def _to_long(x):
    """Kotlin Double.toLong(): NaN -> 0, saturation at the bounds, truncation toward zero."""
    if x != x:
        return 0
    if x >= MAX_LONG:
        return MAX_LONG
    if x <= -MAX_LONG - 1:
        return -MAX_LONG - 1
    return int(x)


def _fini(x):
    return not (math.isinf(x) or math.isnan(x))


# --- springs -----------------------------------------------------------------
def read_springs(path=TOKENS_JSON):
    """{name: (stiffness, damping, token_names)} read from the ExpressiveMotion section of
    m3e-tokens.json (generated by the m3e-gnome theme repo from androidx ExpressiveMotionTokens.kt)."""
    section = json.loads(Path(path).read_text(encoding="utf-8"))["ExpressiveMotion"]
    springs = {}
    for name in SPRING_NAMES:
        keys = (f"Spring{name}Stiffness", f"Spring{name}Damping")
        for key in keys:
            if key not in section:
                raise ValueError(f"spring token not found in {path}: {key}")
        springs[name] = (float(section[keys[0]]["valeur"]), float(section[keys[1]]["valeur"]))
    return springs


# --- SpringSimulation.kt ----------------------------------------------------
def state(stiffness, damping, x0, v0, t_ms):
    """Displacement and velocity (units/s) at t_ms, final position 0.
    Port of SpringSimulation.updateValues (SpringSimulation.kt:98)."""
    naturalFreq = math.sqrt(stiffness)  # SpringSimulation.kt:46
    dampingRatio = damping
    adjustedDisplacement = x0  # finalPosition = 0 ; SpringSimulation.kt:103
    lastVelocity = v0
    deltaT = t_ms / 1000.0  # SpringSimulation.kt:104
    dampingRatioSquared = dampingRatio * dampingRatio
    r = -dampingRatio * naturalFreq

    if dampingRatio > 1:  # SpringSimulation.kt:111 (overdamped)
        s = naturalFreq * math.sqrt(dampingRatioSquared - 1)
        gammaPlus = r + s
        gammaMinus = r - s
        coeffB = (gammaMinus * adjustedDisplacement - lastVelocity) / (gammaMinus - gammaPlus)
        coeffA = adjustedDisplacement - coeffB
        displacement = coeffA * math.exp(gammaMinus * deltaT) + coeffB * math.exp(gammaPlus * deltaT)
        velocity = (coeffA * gammaMinus * math.exp(gammaMinus * deltaT)
                   + coeffB * gammaPlus * math.exp(gammaPlus * deltaT))
    elif dampingRatio == 1.0:  # SpringSimulation.kt:125 (critical)
        coeffA = adjustedDisplacement
        coeffB = lastVelocity + naturalFreq * adjustedDisplacement
        nFdT = -naturalFreq * deltaT
        displacement = (coeffA + coeffB * deltaT) * math.exp(nFdT)
        velocity = ((coeffA + coeffB * deltaT) * math.exp(nFdT) * (-naturalFreq)) + coeffB * math.exp(nFdT)
    else:  # SpringSimulation.kt:135 (underdamped)
        dampedFreq = naturalFreq * math.sqrt(1 - dampingRatioSquared)
        cosCoeff = adjustedDisplacement
        sinCoeff = (1 / dampedFreq) * ((-r * adjustedDisplacement) + lastVelocity)
        dFdT = dampedFreq * deltaT
        displacement = math.exp(r * deltaT) * (cosCoeff * math.cos(dFdT) + sinCoeff * math.sin(dFdT))
        velocity = (displacement * r
                   + math.exp(r * deltaT)
                   * (-dampedFreq * cosCoeff * math.sin(dFdT) + dampedFreq * sinCoeff * math.cos(dFdT)))
    return (displacement, velocity)


# --- SpringEstimation.kt ----------------------------------------------------
def _newton(x, fn, fn_prime):
    return x - _div(fn(x), fn_prime(x))


def _estimate_underdamped(firstRootReal, firstRootImaginary, p0, v0, delta):
    """SpringEstimation.kt:128"""
    r = firstRootReal
    c1 = p0
    c2 = _div(v0 - r * c1, firstRootImaginary)
    c = math.sqrt(c1 * c1 + c2 * c2)
    return _div(_ln(_div(delta, c)), r)


def _estimate_critical(firstRootReal, p0, v0, delta):
    """SpringEstimation.kt:147"""
    r = firstRootReal
    c1 = p0
    c2 = v0 - r * c1
    t1 = _div(_ln(abs(_div(delta, c1))), r)
    guess = _ln(abs(_div(delta, c2)))
    t = guess
    for _ in range(6):  # for (i in 0..5)
        t = guess - _ln(abs(_div(t, r)))
    t2 = _div(t, r)
    if not _fini(t1):
        tCurr = t2
    elif not _fini(t2):
        tCurr = t1
    else:
        tCurr = max(t1, t2)

    tInflection = -_div(r * c1 + c2, r * c2)
    xInflection = c1 * _exp(r * tInflection) + c2 * tInflection * _exp(r * tInflection)

    if tInflection != tInflection or tInflection <= 0.0:
        signedDelta = -delta
    elif tInflection > 0.0 and -xInflection < delta:
        if c2 < 0 and c1 > 0:
            tCurr = 0.0
        signedDelta = -delta
    else:
        tCurr = -(2.0 / r) - _div(c1, c2)
        signedDelta = delta

    tDelta = math.inf  # Double.MAX_VALUE
    iterations = 0
    while tDelta > 0.001 and iterations < 100:
        iterations += 1
        tLast = tCurr
        tCurr = _newton(
            tCurr,
            lambda t: (c1 + c2 * t) * _exp(r * t) + signedDelta,
            lambda t: (c2 * (r * t + 1) + c1 * r) * _exp(r * t),
        )
        tDelta = abs(tLast - tCurr)
    return tCurr


def _estimate_overdamped(firstRootReal, secondRootReal, p0, v0, delta):
    """SpringEstimation.kt:227"""
    r1 = firstRootReal
    r2 = secondRootReal
    c2 = _div(r1 * p0 - v0, r1 - r2)
    c1 = p0 - c2
    t1 = _div(_ln(abs(_div(delta, c1))), r1)
    t2 = _div(_ln(abs(_div(delta, c2))), r2)
    if not _fini(t1):
        tCurr = t2
    elif not _fini(t2):
        tCurr = t1
    else:
        tCurr = max(t1, t2)

    tInflection = _div(_ln(_div(c1 * r1, -c2 * r2)), r2 - r1)

    def x_inflection():
        return c1 * _exp(r1 * tInflection) + c2 * _exp(r2 * tInflection)

    if tInflection != tInflection or tInflection <= 0.0:
        signedDelta = -delta
    elif tInflection > 0.0 and -x_inflection() < delta:
        if c2 > 0.0 and c1 < 0.0:
            tCurr = 0.0
        signedDelta = -delta
    else:
        tCurr = _div(_ln(_div(-(c2 * r2 * r2), c1 * r1 * r1)), r1 - r2)
        signedDelta = delta

    # good initial guess: return directly
    if abs(c1 * r1 * _exp(r1 * tCurr) + c2 * r2 * _exp(r2 * tCurr)) < 0.0001:
        return tCurr
    tDelta = math.inf
    iterations = 0
    while tDelta > 0.001 and iterations < 100:
        iterations += 1
        tLast = tCurr
        tCurr = _newton(
            tCurr,
            lambda t: c1 * _exp(r1 * t) + c2 * _exp(r2 * t) + signedDelta,
            lambda t: c1 * r1 * _exp(r1 * t) + c2 * r2 * _exp(r2 * t),
        )
        tDelta = abs(tLast - tCurr)
    return tCurr


def _estimate_internal(firstRootReal, firstRootImaginary, secondRootReal, dampingRatio,
                     initialVelocity, initialPosition, delta):
    """SpringEstimation.kt:305"""
    if initialPosition == 0.0 and initialVelocity == 0.0:
        return 0
    v0 = -initialVelocity if initialPosition < 0 else initialVelocity
    p0 = abs(initialPosition)
    if dampingRatio > 1.0:
        t = _estimate_overdamped(firstRootReal, secondRootReal, p0, v0, delta)
    elif dampingRatio < 1.0:
        t = _estimate_underdamped(firstRootReal, firstRootImaginary, p0, v0, delta)
    else:
        t = _estimate_critical(firstRootReal, p0, v0, delta)
    return _to_long(t * 1000.0)


def duration_ms(stiffness, damping, v0, x0, threshold):
    """Port of estimateAnimationDurationMillis (SpringEstimation.kt:36 and :59).

    Faithful to Compose, WITHOUT a shortcut for |x0| <= threshold: Compose does not short-circuit.
    For x0 = +-0.3, v0 = 0, threshold 0.5, ln(threshold/c) is positive while the root is negative,
    so the result can be negative or zero: 0 ms (DefaultSpatial, SlowSpatial), -16 ms (FastSpatial),
    -51 ms (DefaultEffects) and down to -72 ms (SlowEffects); see tests/unit/data/reference-values.json.
    Callers (spring.js) handle |x0| <= threshold separately (duration 0, immediate end); this module
    deliberately does not.
    """
    if damping == 0:  # SpringEstimation.kt:44
        return MAX_LONG_MILLIS
    dampingCoefficient = 2.0 * damping * math.sqrt(stiffness)  # :66
    partialRoot = dampingCoefficient * dampingCoefficient - 4.0 * stiffness
    partialRootReal = 0.0 if partialRoot < 0.0 else math.sqrt(partialRoot)
    partialRootImaginary = math.sqrt(abs(partialRoot)) if partialRoot < 0.0 else 0.0
    firstRootReal = (-dampingCoefficient + partialRootReal) * 0.5
    firstRootImaginary = partialRootImaginary * 0.5
    secondRootReal = (-dampingCoefficient - partialRootReal) * 0.5
    return _estimate_internal(firstRootReal, firstRootImaginary, secondRootReal,
                            damping, v0, x0, threshold)



# --- reference values grid ---------------------------------------------------
X0S = [-2000, -400, -40, -0.3, 40, 400, 2000]
V0S = [-20000, -1000, 0, 1000, 20000]
TS_MS = [0, 8, 16, 50, 100, 250, 500, 1000]
THRESHOLDS = [0.5, 0.01]


def generate():
    springs = read_springs()
    states, durations = [], []
    for name, (k, z) in springs.items():
        for x0 in X0S:
            for v0 in V0S:
                for t in TS_MS:
                    x, v = state(k, z, x0, v0, t)
                    states.append({"spring": name, "stiffness": k, "damping": z,
                                   "x0": x0, "v0": v0, "tMs": t, "x": x, "v": v})
                for threshold in THRESHOLDS:
                    durations.append({"spring": name, "stiffness": k, "damping": z,
                                      "x0": x0, "v0": v0, "threshold": threshold,
                                      "ms": duration_ms(k, z, v0, x0, threshold)})
    return {"states": states, "durations": durations}


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--write", metavar="FILE", help="write the reference values grid")
    a = p.parse_args()
    if a.write:
        with open(a.write, "w", encoding="utf-8") as f:
            json.dump(generate(), f, ensure_ascii=False, indent=1)
            f.write("\n")


if __name__ == "__main__":
    main()
