#!/usr/bin/env python3
"""Single generator of the M3E motion data.

Reads shared/data/{m3e-tokens.json, patterns-source.json, android-source.json} and writes
  shared/m3e/tokens.js               (frozen constants imported by the toolkit),
  shared/generated/m3e-motion.json   (all data, including the provenance of every spring),
  shared/generated/gtk/m3e-gtk{3,4}-motion.css  (GTK spring table as cubic-bezier + duration).
Never edit the outputs by hand. `--check` fails when the committed outputs are stale.
"""
import argparse
import json
import math
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import bezier  # noqa: E402
import compose_ref  # noqa: E402

ROOT = HERE.parent
DATA = ROOT / "shared" / "data"
TOKENS_JSON = DATA / "m3e-tokens.json"
PATTERNS_SOURCE = DATA / "patterns-source.json"
ANDROID_SOURCE = DATA / "android-source.json"
CURVE_POINTS = 400

NAMES = compose_ref.SPRING_NAMES
THRESHOLDS = {"px": 0.5, "unit": 0.01, "degree": 0.1}
GTK_DISTANCE = 40.0   # logical px: typical distance of the GTK table
GTK_POINTS = 400
ERROR_LIMIT_PCT = 5.0
JS_HEADER = "// Generated by tools/generate.py — do not edit.\n"


def read_springs():
    """Springs from the ExpressiveMotion section of m3e-tokens.json."""
    pairs = compose_ref.read_springs(TOKENS_JSON)
    return {name: {
        "stiffness": k,
        "damping": z,
        "origin": f"m3e-tokens.json ExpressiveMotion.Spring{name}Stiffness / Spring{name}Damping "
                  "(androidx ExpressiveMotionTokens.kt)",
    } for name, (k, z) in pairs.items()}


def read_patterns():
    return json.loads(PATTERNS_SOURCE.read_text(encoding="utf-8"))


def accelerate_decelerate_curve():
    """Android's AccelerateDecelerateInterpolator (cos((x + 1)·π)/2 + 0.5), the default interpolator of
    an ObjectAnimator, fitted with one cubic segment (bezier.py). Returns (segments, error_pct)."""
    pts = [(i / (CURVE_POINTS - 1), math.cos((i / (CURVE_POINTS - 1) + 1) * math.pi) / 2 + 0.5)
           for i in range(CURVE_POINTS)]
    (x1, y1, x2, y2), err = bezier.fit(pts)
    return [[0, 0, x1, y1, x2, y2, 1, 1]], round(err * 100, 2)


def read_android():
    android = json.loads(ANDROID_SOURCE.read_text(encoding="utf-8"))
    for name in android["springs"]:
        if name in NAMES:
            raise SystemExit(f"Android spring {name}: same name as a Compose spring")
    segments, err = accelerate_decelerate_curve()
    android["curves"]["AccelerateDecelerate"] = {
        "segments": segments,
        "segments_origin": ("androidx/SwitchCompat.java:1131-1134 (ObjectAnimator without interpolator: "
                            "AccelerateDecelerateInterpolator, cos((x + 1)·π)/2 + 0.5); cubic segment fitted by "
                            f"tools/bezier.py, max error {err:g} % of the travel"),
    }
    return android


def runtime_data(node):
    """Runtime data: without `_convention` and without `*_origin` fields."""
    if isinstance(node, dict):
        return {k: runtime_data(v) for k, v in node.items()
                if k != "_convention" and not k.endswith("_origin")}
    if isinstance(node, list):
        return [runtime_data(v) for v in node]
    return node


def dump_json(data):
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def kebab(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def gtk_table(springs):
    """For each spring: fitted cubic-bezier, duration (ms) and max error (% of the travel)."""
    table = {}
    for name, spring in springs.items():
        k, c = spring["stiffness"], spring["damping"]
        duration = compose_ref.duration_ms(k, c, 0.0, GTK_DISTANCE, THRESHOLDS["px"])
        curve = []
        for i in range(GTK_POINTS):
            tau = i / (GTK_POINTS - 1)
            x, _ = compose_ref.state(k, c, GTK_DISTANCE, 0.0, tau * duration)
            curve.append((tau, 1.0 - x / GTK_DISTANCE))
        (x1, y1, x2, y2), err = bezier.fit(curve)
        table[name] = {"curve": [x1, y1, x2, y2], "durationMs": int(duration),
                       "errorPct": round(err * 100, 2)}
    return table


def build():
    springs = read_springs()
    return {"springs": springs, "thresholds": THRESHOLDS, "patterns": read_patterns(),
            "gtk": gtk_table(springs), "android": read_android()}


def _bezier_css(curve):
    return "cubic-bezier(" + ", ".join(f"{v:g}" for v in curve) + ")"


def render_gtk_css(data):
    header = ("/* Generated by the m3e-motion generator - do not edit.\n"
              f" * GTK table of the M3E springs: cubic-bezier fitted on a {GTK_DISTANCE:g} px displacement,\n"
              " * duration = settling time of the spring (0.5 px threshold). */\n")
    g4 = [header, ":root {"]
    g3 = [header + "/* GTK 3 has no CSS variables: inert example rules to copy. */\n"]
    for name in NAMES:
        t = data["gtk"][name]
        k, curve = kebab(name), _bezier_css(t["curve"])
        g4.append(f"  --m3e-spring-{k}-curve: {curve}; /* max error {t['errorPct']:g} % */")
        g4.append(f"  --m3e-spring-{k}-duration: {t['durationMs']}ms;")
        g3.append(f".m3e-spring-{k} {{\n"
                  f"  transition-duration: {t['durationMs']}ms; /* M3E.Spring.{name} */\n"
                  f"  transition-timing-function: {curve}; /* max error {t['errorPct']:g} % */\n}}\n")
    g4.append("}\n")
    return {"gtk/m3e-gtk4-motion.css": "\n".join(g4), "gtk/m3e-gtk3-motion.css": "\n".join(g3)}


def render_tokens_js(data):
    android = data["android"]
    springs = {n: {"stiffness": s["stiffness"], "damping": s["damping"]}
               for n, s in {**data["springs"], **android["springs"]}.items()}
    patterns = runtime_data(data["patterns"])
    curves = {n: {"segments": c["segments"]} for n, c in android["curves"].items()}
    motions = {"density": android["density"], **runtime_data(android["motions"])}

    def js(v):
        return json.dumps(v, indent=2, sort_keys=True, ensure_ascii=False)

    return (JS_HEADER
            + "\nfunction freeze(o) {\n"
            "    if (o && typeof o === 'object')\n"
            "        Object.values(o).forEach(freeze);\n"
            "    return Object.freeze(o);\n}\n\n"
            f"export const SPRINGS = freeze({js(springs)});\n\n"
            f"export const THRESHOLDS = freeze({js(data['thresholds'])});\n\n"
            f"export const PATTERNS = freeze({js(patterns)});\n\n"
            "// Android 17 (android-source.json): fixed-duration curves (curve.js) and motion parameters.\n"
            f"export const CURVES = freeze({js(curves)});\n\n"
            f"export const ANDROID = freeze({js(motions)});\n")


def render_all(data):
    """{path relative to the repository root: text}."""
    files = {"shared/m3e/tokens.js": render_tokens_js(data),
             "shared/generated/m3e-motion.json": dump_json(data)}
    for rel, text in render_gtk_css(data).items():
        files[f"shared/generated/{rel}"] = text
    return files


def report_errors(data):
    for name in NAMES:
        e = data["gtk"][name]["errorPct"]
        if e > ERROR_LIMIT_PCT:
            print(f"WARNING {name}: Bezier/spring error {e:g} % > {ERROR_LIMIT_PCT:g} %")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", default=str(ROOT), help="output root directory (default: the repository)")
    p.add_argument("--check", action="store_true", help="fail if the committed outputs are stale")
    args = p.parse_args()
    data = build()
    files = render_all(data)
    report_errors(data)
    root = Path(args.out)
    if args.check:
        stale = [rel for rel, text in files.items()
                 if not (root / rel).is_file() or (root / rel).read_text(encoding="utf-8") != text]
        if stale:
            print("stale generated files (run python3 tools/generate.py):\n  " + "\n  ".join(stale))
            return 1
        print("generated files are up to date")
        return 0
    for rel, text in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
