"""Tests of bezier.py and of the GTK table generated by generate.py."""
import json
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
import bezier  # noqa: E402

NAMES = ("DefaultSpatial", "FastSpatial", "SlowSpatial",
         "DefaultEffects", "FastEffects", "SlowEffects")


def samples(x1, y1, x2, y2, n=400):
    return [(i / (n - 1), bezier.value(x1, y1, x2, y2, i / (n - 1))) for i in range(n)]


class TestBezier(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory()
        cls.generated = subprocess.run([sys.executable, str(ROOT / "tools" / "generate.py"), "--out", cls.tmp.name],
                                 check=True, capture_output=True, text=True)
        cls.out = Path(cls.tmp.name) / "shared" / "generated"
        cls.gtk = json.loads((cls.out / "m3e-motion.json").read_text())["gtk"]

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def test_fits_known_bezier(self):
        target = (0.2, 0.0, 0.0, 1.0)
        (p, err) = bezier.fit(samples(*target))
        for a, b in zip(p, target):
            self.assertAlmostEqual(a, b, delta=1e-3)
        self.assertLess(err, 0.001)

    def test_x_within_bounds(self):
        for name in NAMES:
            x1, _, x2, _ = self.gtk[name]["curve"]
            self.assertTrue(0 <= x1 <= 1 and 0 <= x2 <= 1, name)

    def test_spatial_overshoot(self):
        self.assertGreater(max(y for _, y in samples(*self.gtk["FastSpatial"]["curve"])), 1.0)

    def test_effects_without_overshoot(self):
        for name in ("DefaultEffects", "FastEffects", "SlowEffects"):
            self.assertLessEqual(max(y for _, y in samples(*self.gtk[name]["curve"])), 1.0 + 1e-3, name)

    def test_error_limit_warning(self):
        warnings = [l for l in self.generated.stdout.splitlines() if l.startswith("WARNING")]
        for name in NAMES:
            e = self.gtk[name]["errorPct"]
            self.assertIsInstance(e, float)
            self.assertEqual(any(name in l for l in warnings), e > 5, name)

    def test_css_structure(self):
        for f in ("m3e-gtk3-motion.css", "m3e-gtk4-motion.css"):
            text = (self.out / "gtk" / f).read_text()
            self.assertEqual(text.count("{"), text.count("}"), f)
            for args in re.findall(r"cubic-bezier\(([^)]*)\)", text):
                x1, y1, x2, y2 = (float(v) for v in args.split(","))
                self.assertTrue(0 <= x1 <= 1 and 0 <= x2 <= 1, f"{f}: {args}")
            self.assertEqual(len(re.findall(r"cubic-bezier\(", text)), len(NAMES), f)

    def test_css_content(self):
        g4 = (self.out / "gtk" / "m3e-gtk4-motion.css").read_text()
        g3 = (self.out / "gtk" / "m3e-gtk3-motion.css").read_text()
        d = self.gtk["DefaultSpatial"]
        self.assertIn("--m3e-spring-default-spatial-curve: cubic-bezier(", g4)
        self.assertIn(f"--m3e-spring-default-spatial-duration: {d['durationMs']}ms;", g4)
        self.assertIn(".m3e-spring-default-spatial", g3)
        self.assertIn("/* M3E.Spring.DefaultSpatial */", g3)


if __name__ == "__main__":
    unittest.main()
