"""Tests of tools/generate.py (json, tokens.js, GTK css)."""
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GENERATE = ROOT / "tools" / "generate.py"

EXPECTED = {
    "DefaultSpatial": (380.0, 0.8),
    "FastSpatial": (800.0, 0.6),
    "SlowSpatial": (200.0, 0.8),
    "DefaultEffects": (1600.0, 1.0),
    "FastEffects": (3800.0, 1.0),
    "SlowEffects": (800.0, 1.0),
}


def generate(directory):
    subprocess.run([sys.executable, str(GENERATE), "--out", str(directory)], check=True, capture_output=True)
    return Path(directory)


def gjs(script_text):
    with tempfile.TemporaryDirectory() as d:
        script = Path(d) / "t.mjs"
        script.write_text(script_text)
        return subprocess.run(["gjs", "-m", str(script)], capture_output=True, text=True)


class TestGenerate(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory()
        cls.out = generate(cls.tmp.name)
        cls.json = json.loads((cls.out / "shared/generated/m3e-motion.json").read_text())

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def test_six_springs(self):
        r = self.json["springs"]
        self.assertEqual(set(r), set(EXPECTED))
        for name, (k, c) in EXPECTED.items():
            self.assertEqual(r[name]["stiffness"], k, name)
            self.assertEqual(r[name]["damping"], c, name)
        self.assertEqual(self.json["thresholds"], {"px": 0.5, "unit": 0.01, "degree": 0.1})

    def test_springs_match_vendored_tokens(self):
        tokens = json.loads((ROOT / "shared/data/m3e-tokens.json").read_text())["ExpressiveMotion"]
        for name, (k, c) in EXPECTED.items():
            self.assertEqual(tokens[f"Spring{name}Stiffness"]["valeur"], k)
            self.assertEqual(tokens[f"Spring{name}Damping"]["valeur"], c)
            self.assertIn(f"Spring{name}Stiffness", self.json["springs"][name]["origin"])

    def test_reproducible(self):
        with tempfile.TemporaryDirectory() as a, tempfile.TemporaryDirectory() as b:
            generate(a)
            generate(b)
            fa = sorted(p.relative_to(a) for p in Path(a).rglob("*") if p.is_file())
            fb = sorted(p.relative_to(b) for p in Path(b).rglob("*") if p.is_file())
            self.assertEqual(fa, fb)
            self.assertIn(Path("shared/generated/m3e-motion.json"), fa)
            self.assertIn(Path("shared/m3e/tokens.js"), fa)
            for f in fa:
                self.assertEqual((Path(a) / f).read_bytes(), (Path(b) / f).read_bytes(), str(f))

    def test_committed_outputs_are_fresh(self):
        r = subprocess.run([sys.executable, str(GENERATE), "--check"], capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)

    def test_patterns_copied(self):
        source = json.loads((ROOT / "shared/data/patterns-source.json").read_text())
        self.assertEqual(self.json["patterns"], source)

    def test_json_format(self):
        text = (self.out / "shared/generated/m3e-motion.json").read_text()
        self.assertTrue(text.endswith("}\n"))
        self.assertEqual(text, json.dumps(self.json, indent=2, sort_keys=True, ensure_ascii=False) + "\n")

    def test_tokens_js_loads(self):
        js = self.out / "shared/m3e/tokens.js"
        self.assertTrue(js.read_text().startswith("// Generated by tools/generate.py — do not edit."))
        r = gjs(f"import {{ SPRINGS, THRESHOLDS, PATTERNS }} from 'file://{js}';\n"
                "print(SPRINGS.FastSpatial.damping);\n"
                "print(Object.keys(SPRINGS.FastSpatial).join(','));\n"
                "print(Object.isFrozen(SPRINGS.FastSpatial), Object.isFrozen(PATTERNS), THRESHOLDS.px);\n"
                "print(JSON.stringify(PATTERNS).includes('_origin'), '_convention' in PATTERNS);\n")
        self.assertEqual(r.returncode, 0, r.stderr)
        lines = r.stdout.splitlines()
        self.assertEqual(lines[0], "0.6")
        self.assertEqual(sorted(lines[1].split(",")), ["damping", "stiffness"])
        self.assertEqual(lines[2], "true true 0.5")
        self.assertEqual(lines[3], "false false")

    def test_android_provenance(self):
        """Every scalar of android-source.json and patterns-source.json has an _origin sibling that names a
        pinned upstream file (with a line number), a measurement or a design decision."""
        prefixes = ("aosp-frameworks-base/", "aosp-frameworks-libs-systemui/", "aosp-launcher3/", "mdc-android/",
                    "androidx/", "measured:", "M3E-visual:", "design decision:", "m3e-gnome theme",
                    "m3.material.io", "https://")
        for name in ("android-source.json", "patterns-source.json"):
            data = json.loads((ROOT / "shared/data" / name).read_text())

            def walk(o, where):
                if not isinstance(o, dict):
                    return
                for k, v in o.items():
                    if k.endswith("_origin") or k == "_convention":
                        continue
                    if isinstance(v, (int, float, str, bool)) or (isinstance(v, list) and k == "segments"):
                        self.assertIn(f"{k}_origin", o, f"{name} {where}.{k}")
                        origin = o[f"{k}_origin"]
                        self.assertTrue(origin.startswith(prefixes), f"{name} {where}.{k}: {origin}")
                    else:
                        walk(v, f"{where}.{k}")
            walk(data, "$")

    def test_no_french_leftovers_in_data(self):
        for name in ("android-source.json", "patterns-source.json"):
            text = (ROOT / "shared/data" / name).read_text()
            for word in ("ressort", "raideur", "amortissement", "origine", "m3e-reference/", "docs/"):
                self.assertNotIn(word, text, f"{name}: {word}")

    def test_android_tokens(self):
        r = self.json["android"]["springs"]
        self.assertEqual((r["ComposeSpringDefault"]["stiffness"], r["ComposeSpringDefault"]["damping"]), (1500.0, 1.0))
        self.assertEqual((r["VolumeDialog"]["stiffness"], r["VolumeDialog"]["damping"]), (700.0, 0.9))
        self.assertEqual((r["NotificationTranslation"]["stiffness"], r["NotificationTranslation"]["damping"]),
                         (380.0, 0.68))
        js = self.out / "shared/m3e/tokens.js"
        res = gjs(f"import {{ SPRINGS, CURVES, ANDROID }} from 'file://{js}';\n"
                  "print(SPRINGS.DefaultSpatial.stiffness, SPRINGS.GestureHomeX.stiffness, "
                  "SPRINGS.DialogLaunchScale.damping);\n"
                  "print(CURVES.Emphasized.segments.length, ANDROID.banner.durationMs, Object.isFrozen(ANDROID));\n"
                  "print(JSON.stringify(ANDROID).includes('_origin'));\n")
        self.assertEqual(res.returncode, 0, res.stderr)
        self.assertEqual(res.stdout.splitlines(), ["380 450 1.3", "2 400 true", "false"])


if __name__ == "__main__":
    unittest.main()
